// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"context"
	"test.com/wire/db"
	"test.com/wire/service"
)

// Injectors from wire.go:

func initApp(ctx context.Context) *App {
	car := service.NewCar(ctx)
	city := db.NewCity(ctx)
	address := db.NewAddress(ctx, city)
	person := service.NewPerson(ctx, car, address)
	app := NewApp(ctx, person)
	return app
}
